<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" 
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                exclude-result-prefixes="sitemap">
	<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml">
			<head>
				<title>XML Sitemap | Arvello Creative</title>
				<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
				<style type="text/css">
					body {
						font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
						color: #e2e8f0;
						background-color: #0f172a;
						margin: 0;
						padding: 40px 20px;
					}
					#sitemap {
						max-width: 1000px;
						margin: 0 auto;
					}
					#sitemap__header {
						margin-bottom: 40px;
						border-bottom: 1px solid #334155;
						padding-bottom: 20px;
					}
					#sitemap__header h1 {
						font-size: 28px;
						margin: 0 0 10px 0;
						color: #f8fafc;
					}
					#sitemap__header p {
						font-size: 14px;
						color: #94a3b8;
						margin: 0;
					}
					#sitemap__header a {
						color: #3b82f6;
						text-decoration: none;
					}
					#sitemap__header a:hover {
						text-decoration: underline;
					}
					.count {
						background: #1e293b;
						color: #60a5fa;
						padding: 4px 10px;
						border-radius: 6px;
						font-size: 12px;
						font-weight: 600;
						margin-left: 10px;
					}
					table {
						width: 100%;
						border-collapse: collapse;
						margin-top: 20px;
						background: #1e293b;
						border-radius: 12px;
						overflow: hidden;
						box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
					}
					th {
						text-align: left;
						padding: 16px;
						background: #334155;
						color: #f8fafc;
						font-size: 13px;
						text-transform: uppercase;
						letter-spacing: 0.05em;
					}
					td {
						padding: 16px;
						border-bottom: 1px solid #334155;
						font-size: 14px;
						color: #cbd5e1;
					}
					tr:last-child td {
						border-bottom: none;
					}
					tr:hover td {
						background: #334155;
						color: #f8fafc;
					}
					a {
						color: #60a5fa;
						text-decoration: none;
					}
					a:hover {
						text-decoration: underline;
					}
					.lastmod {
						color: #94a3b8;
						font-variant-numeric: tabular-nums;
					}
				</style>
			</head>
			<body>
				<div id="sitemap">
					<div id="sitemap__header">
						<h1>XML Sitemap <span class="count">
							<xsl:choose>
								<xsl:when test="sitemap:sitemapindex">
									<xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/> Sitemaps
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs
								</xsl:otherwise>
							</xsl:choose>
						</span></h1>
						<p>Generated by <a href="https://www.arvellocreative.com">Arvello Creative</a>. This is an XML Sitemap, meant for consumption by search engines like Google.</p>
					</div>
					
					<xsl:choose>
						<xsl:when test="sitemap:sitemapindex">
							<table cellpadding="3">
								<thead>
									<tr>
										<th width="75%">Sitemap URL</th>
										<th width="25%">Last Modified</th>
									</tr>
								</thead>
								<tbody>
									<xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
										<xsl:variable name="sitemap_url">
											<xsl:value-of select="sitemap:loc"/>
										</xsl:variable>
										<tr>
											<td>
												<a href="{$sitemap_url}">
													<xsl:value-of select="sitemap:loc"/>
												</a>
											</td>
											<td class="lastmod">
												<xsl:value-of select="sitemap:lastmod"/>
											</td>
										</tr>
									</xsl:for-each>
								</tbody>
							</table>
						</xsl:when>
						<xsl:otherwise>
							<table cellpadding="3">
								<thead>
									<tr>
										<th width="70%">URL</th>
										<th width="15%">Priority</th>
										<th width="15%">Last Mod.</th>
									</tr>
								</thead>
								<tbody>
									<xsl:for-each select="sitemap:urlset/sitemap:url">
										<tr>
											<td>
												<xsl:variable name="item_url">
													<xsl:value-of select="sitemap:loc"/>
												</xsl:variable>
												<a href="{$item_url}">
													<xsl:value-of select="sitemap:loc"/>
												</a>
											</td>
											<td>
												<xsl:value-of select="sitemap:priority"/>
											</td>
											<td class="lastmod">
												<xsl:value-of select="sitemap:lastmod"/>
											</td>
										</tr>
									</xsl:for-each>
								</tbody>
							</table>
						</xsl:otherwise>
					</xsl:choose>
				</div>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
